export const state = {
  subject: localStorage.getItem("kv-subject") || "admin",
  scopePath: localStorage.getItem("kv-scope") || "production",
  page: "overview",
  groupBy: "rack",
  metric: "cpu",
  heatmapType: "node",
  // Whether the operator chose that tier themselves. Until they do, the
  // heatmap opens on one that has something in it.
  heatmapTypePinned: false,
  metricMinutes: 60,
  overviewHealth: "all",
  overviewGroup: "all",
  anomaliesOnly: false,
  selectedResourceId: null,
  selectedResource: null,
  selectedAgentId: null,
  selectedIncidentId: null,
  incidentEvents: [],
  resourceMetrics: [],
  detailTab: "summary",
  agentTab: "hardware",
  subFilter: "",
  subQuery: "",
  activeTerminalTab: null,
  // How much of the docked shell is showing: "collapsed" (a bar in the
  // corner), "open", or "max". Collapsed at rest, so the panel never sits on
  // top of the page underneath.
  terminalDock: "collapsed",
  query: "",
  resourceType: "",
  resourceHealth: "",
  resourceLifecycle: "",
  metricRange: "",
  resourceOffset: 0,
  resourcePageSize: 100,
  pager: {},
  listPageSize: 20,
  alerts: 7,
  sidebarCollapsed: localStorage.getItem("kv-sidebar") === "collapsed",
  mobileSidebarOpen: false,
  navStack: [],
  userMenuOpen: false,
  mapGroupBy: "",
  mapQuery: "",
  mapLoad: "all",
  mapExpanded: new Set(),
  liveAgents: [],
  liveInventories: [],
  liveResources: [],
  liveFilteredResources: [],
  liveResourceTotal: 0,
  liveRelations: [],
  liveGroups: [],
  liveMemberships: [],
  liveMetrics: null,
  liveMetricSeries: [],
  liveOverview: null,
  liveUtilization: null,
  utilFilter: "all",
  utilQuery: "",
  utilTab: "nodes",
  // Which number the workload ranking answers. A memory incident is not
  // served by a list sorted by CPU.
  workloadSort: "cpu",
  alertFilter: "all",
  // Alerts picked to become one incident, held by id so the choice survives
  // filtering, paging and the periodic refresh.
  alertsPicked: [],
  incidentFilter: "all",
  opQuery: "",
  opStatus: "all",
  execQuery: "",
  execFilter: "all",
  terminalQuery: "",
  terminalFilter: "all",
  logTarget: "",
  logSource: "live",
  logLevel: "all",
  // What a read asks the node for: which half of its journal, and which
  // severity band. The live view carries named senders, so neither is a
  // question it can answer.
  logReadSource: "host",
  logBand: "",
  // Lines picked out of a read, held by their own text so a choice survives
  // paging and the periodic refresh.
  logPicked: [],
  logQuery: "",
  serviceFilter: "all",
  serviceQuery: "",
  workloadType: "all",
  workloadQuery: "",
  logCapture: null,
  logWindowMinutes: 60,
  liveLogLines: [],
  liveLogCounters: [],
  userQuery: "",
  userStatus: "all",
  liveAlerts: [],
  liveIncidents: [],
  liveRoles: [],
  liveScopes: [],
  liveBindings: [],
  liveOperations: [],
  liveAlertRules: [],
  liveAlertSilences: [],
  liveAlertInhibitions: [],
  liveNotificationChannels: [],
  liveNotificationRoutes: [],
  liveNotificationDeliveries: [],
  liveRunbooks: [],
  liveExecutions: [],
  liveTerminals: [],
  liveAudit: [],
  auditTotal: 0,
  auditOffset: 0,
  auditPageSize: 200,
  permissions: {},
  apiOnline: false,
  lastSyncAt: null,
  auth: { authenticated: false },
  liveUsers: [],
  liveTeams: [],
  // Timeline entries from before the incident was declared are folded away:
  // the default question is "what have we done about this", and the evidence
  // from before is one click behind it.
  incidentHistoryOpen: false,
  incidentChecksOpen: false,
};
