#!/usr/bin/env sh
# Writes .env with randomly generated secrets.
#
#   tools/gen-env.sh                            # generate .env
#   tools/gen-env.sh --url https://kv.example   # and declare the public address
#   tools/gen-env.sh --force                    # overwrite an existing .env
#
# Values are hex, so nothing in them needs quoting or escaping in an env file.
# The generated admin password is printed once and not stored anywhere else.
set -eu

OUT=".env"
FORCE=0
PUBLIC_URL=""
while [ $# -gt 0 ]; do
	case "$1" in
	--force) FORCE=1 ;;
	--url) shift; PUBLIC_URL="${1:-}" ;;
	--out) shift; OUT="${1:-.env}" ;;
	-h | --help)
		sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
		exit 0
		;;
	*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
	shift
done

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

if [ -e "$OUT" ] && [ "$FORCE" -eq 0 ]; then
	# Regenerating over a live deployment breaks it: the database was
	# initialised with the old password, and enrolled agents hold credentials
	# derived from the old key.
	echo "$OUT already exists. Pass --force to replace it." >&2
	echo "Replacing secrets on a running deployment locks out the database and every enrolled agent." >&2
	exit 1
fi

# Lengths follow the server's own rules: the token needs 16 characters and the
# credential key 32, and the two must differ.
ENROLLMENT_TOKEN=$(openssl rand -hex 16)
CREDENTIAL_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
ADMIN_PASSWORD=$(openssl rand -hex 12)

umask 077
cat > "$OUT" <<ENV
# Generated by tools/gen-env.sh. Secrets are random; keep this file out of git.

# Shared by the server and every agent it enrols.
KLOUDVIEW_ENROLLMENT_TOKEN=$ENROLLMENT_TOKEN
# Server-only. Must differ from the enrollment token.
KLOUDVIEW_AGENT_CREDENTIAL_KEY=$CREDENTIAL_KEY
# Read by PostgreSQL on first initialisation; changing it later needs the
# database role altered to match.
KLOUDVIEW_POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Initial console admin account, seeded on first start (login: admin / <this>).
KLOUDVIEW_ADMIN_PASSWORD=$ADMIN_PASSWORD

# Address operators and agents reach the server on. The startup hardening check
# confirms it is https://, which it cannot detect through a reverse proxy.
KLOUDVIEW_PUBLIC_URL=$PUBLIC_URL

# Agent builds offered for self-update. Populate the directory with
# \`make verify-agent-binaries VERSION=<version>\`; no update is advertised while
# the target is unset.
KLOUDVIEW_AGENT_TARGET_VERSION=

# Node taking a new build first. The rest are offered the version they already
# run until it has held the new one for the soak. Unset updates all at once.
KLOUDVIEW_AGENT_CANARY=
KLOUDVIEW_AGENT_CANARY_SOAK=10m
ENV
chmod 600 "$OUT"

echo "wrote $OUT (mode 600)"
echo
echo "  console login:  admin / $ADMIN_PASSWORD"
echo
echo "This password is not stored anywhere else. Save it now, or change it in the"
echo "console after the first login."
[ -n "$PUBLIC_URL" ] || echo "KLOUDVIEW_PUBLIC_URL is empty; set it to the https address operators use."
